### ISSUE TITLE
Generate Drive Rig - Error

### ISSUE THREAD

**Issue by mond-cz** [cgtinker/blendartrack#5]
Hi, 
I tried to follow your tutorial, but something failed ... can you check it?

Blender run from Terminal (not mentioned, just avoid possible issue).
Data from mobile successfully downloaded and imported as Empties, Deleted Parent Empty, Generated Face Rig ... now when I want to Generate Driver Rig I got an Error. Rig is generated but is not driven by Face Empties.

```
Error: Python: Traceback (most recent call last):
  File "/Users/filip/Library/Application Support/Blender/3.1/scripts/addons/blendartrack-main/src/interface/Operators.py", line 56, in execute
    input_manager.generate_driver_rig()
  File "/Users/filip/Library/Application Support/Blender/3.1/scripts/addons/blendartrack-main/src/management/input_manager.py", line 68, in generate_driver_rig
    rig = armature.get_armature("rig")
  File "/Users/filip/Library/Application Support/Blender/3.1/scripts/addons/blendartrack-main/src/utils/blend/armature.py", line 10, in get_armature
    armature = bpy.data.objects[name]
KeyError: 'bpy_prop_collection[key]: key "rig" not found'
```
[test_blendartrack_face_rig.blend.zip](https://github.com/cgtinker/blendartrack/files/8053690/test_blendartrack_face_rig.blend.zip)

Thank you for info and your hard work ... it looks awesome :)

**Comment by cgtinker** [comment]
Yeah 3.1 isn't supported yet. The official version 3.0 should work though :)
