### ISSUE TITLE
blender 3.1 import data error

### ISSUE THREAD

**Issue by SHIELDXIE** [cgtinker/blendartrack#9]
### error info：  
  
Python: Traceback (most recent call last):
  File "C:\Users\xnuon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blendartrack-main\src\interface\cgt_operators.py", line 16, in execute
    input_manager.file_to_load(bpy.path.abspath(user.data_path))
  File "C:\Users\xnuon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blendartrack-main\src\management\input_manager.py", line 38, in file_to_load
    manager.import_models(paths)
  File "C:\Users\xnuon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blendartrack-main\src\management\execution_handler.py", line 12, in import_models
    queue_manager = queue.QueueManager(paths)
NameError: name 'queue' is not defined

location: <unknown location>:-1

**Comment by cgtinker** [comment]
damn that it didn't appear in my testing.

fixed it. 
just redownload from main or the release.

**Comment by SHIELDXIE** [comment]
Thinks your reply.It work.😊
